services:
  react:
    image: reactnativecommunity/react-native-android
    command: sh -c 'git config --global --add safe.directory /app && yarn && tail -f /dev/null'
    volumes:
      - ./:/app
    working_dir: /app
